[package]
name = "silex"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Text",
    "Window",
    "DomTokenList",
    "Event",
    "EventTarget",
    "History",
    "Location",
    "console",
    "InputEvent",
    "HtmlInputElement",
    "MouseEvent",
    "ErrorEvent",
    "Comment",
    "DocumentFragment",
    "PromiseRejectionEvent",
    "NodeList",
    "CssStyleDeclaration",
    "SvgElement",
    "HtmlStyleElement",
    "HtmlHeadElement",
] }
js-sys = "0.3"
slotmap = "1.1.1"
wasm-bindgen-futures = "0.4.56"

silex_macros = { path = "../silex_macros" }
