[package]
name = "silex_showcase"
version.workspace = true
edition.workspace = true

[dependencies]
silex.workspace = true
silex_macros.workspace = true
gloo-timers = { version = "0.3", features = ["futures"] }
