[package]
name = "silex_showcase"
version = "0.1.0"
edition = "2024"

[dependencies]
silex = { path = "../../silex" }
gloo-timers = { version = "0.3", features = ["futures"] }
silex_macros = { path = "../../silex_macros" }
