[package]
name = "silex_core"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
wasm-bindgen-futures = { workspace = true }
silex_reactivity = { path = "../silex_reactivity" }
