[package]
name = "silex_core"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
slotmap = { workspace = true }
wasm-bindgen-futures = { workspace = true }
