[package]
name = "silex_dom"
version = "0.1.0"
edition = "2024"

[dependencies]
silex_core = { path = "../silex_core", version = "0.1.0" }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }